export { default as Navbar } from './nav/Navbar'
export { default as Home } from './home/Home'
export { default as Service } from './service/Service'
export { default as Project } from './project/Project'
// export { default as Navbar } from './nav/Navbar'